config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :pictures
  root 'pictures#index'
  
  get '/pages', to: 'pages#about'
  get '/pages', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_attached_file :avatar, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :avatar, content_type: ["image/jpeg", "image/gif", "image/png"]
end

app/models/user.rb
class User < ApplicationRecord
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end





 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def about
    end
    
    def contact
    end
    
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
    
  end

  def new
    @picture = Picture.new
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end
  
  def create
    @picture = Picture.new(picture_params)
    
    if @picture.save
    redirect_to @picture
    else
      render 'new'
    end
    
  end
  
  def update
    @picture = Picture.find(params[:id])
    
    if @picture.update(picture_params)
      redirect_to @picture
    else
      render 'edit'
    end
  end
  
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    
    redirect_to pictures_path
  end
  
  
  private
  
  def picture_params
    params.require(:picture).permit(:title, :body, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
         log_in user
         params[:session][:remember_me] == '1' ? remember(user) : forget(user)
         redirect_back_or user
         
      else
         flash.now[:danger] = 'メールとパスワードの組み合わせが正しくありません'
         render 'new'
      end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in_user, only: [:index, :edit, :update]
   before_action :correct_user,   only: [:edit, :update]
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
    redirect_to @user
    else
      render 'new'
    end
    
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報の更新に成功しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to users_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, )
  end
  
  # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
      store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
   def full_title(page_title = '')
      base_title = "picture app"
         if page_title.empty?
          base_title
         else
          page_title + " | " + base_title
         end
end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    # Remembers a user in a persistent session.
    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end
    
    # Returns true if the given user is the current user.
    def current_user?(user)
      user == current_user
    end

    
    # Returns the current logged-in user (if any).
    def current_user
        if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
       elsif (user_id = cookies.signed[:user_id])
       raise       # The tests still pass, so this branch is currently untested.
        user = User.find_by(id: user_id)
       if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
       end
    end


    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end
    
     # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
    
    # Logs out the current user.
    def log_out
        forget(current_user)
      session.delete(:user_id)
      @current_user = nil
    end
    
    # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
     session[:forwarding_url] = request.original_url if request.get?
  end

    
end

app/helpers/users_helper.rb
module UsersHelper
    
# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end    
end

app/views/layouts/_footer.html.erb
<footer class="footer">

<nav>
 <ul>
    <li><%= link_to "About",  '#' %></li>
    <li><%= link_to "Contact", '#'  %></li>
     
 </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
         <div class="container">
          <%= link_to "Picture App",root_path,  id: "logo" %>
           <nav>
              <ul class="nav navbar-nav navbar-right">
               
               <li><%= link_to "サインアップ", signup_path %></li>
               
               <% if logged_in? %>
                   <li><%= link_to "Users", users_path %></li>
                   <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       Account <b class="caret"></b>
                   </a>
                   <ul class="dropdown-menu">
                       <li><%= link_to "プロフィール", current_user %></li>
                       <li><%= link_to "設定", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                       <li>
                       <%= link_to "ログアウト", logout_path, method: :delete %>
                       </li>
                     </ul>
                   </li>
                <% else %>
                   <li><%= link_to "ログイン", login_path %></li>
                <% end %>
               
              </ul>
           </nav>
         </div>
        </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
  <head>
  <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
   <%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= render 'layouts/shim' %>
   </head>
     <body>
       <%= render 'layouts/header' %>
          <div class="container">
           <% flash.each do |message_type, message| %>
           <div class="alert alert-<%= message_type %>"><%= message %></div>
           <% end %>
                <%= yield %>
            </div>
       <%= render 'layouts/footer' %>
    </body>
</html>

app/views/pages/about.html.erb
<h1>このサイトについて</h1>

<p>このサイトは画像を共有するサイトです</p>

app/views/pages/contact.html.erb
<h1>コンタクト</h1>

<p>連絡はこちらへ</p>

app/views/pictures/_form.html.erb
<%= form_for @user, url: users_path, html: { multipart: true } do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit %>
<% end %>

app/views/pictures/edit.html.erb
<% provide(:title, "画像の編集") %>

<div class="container picture-edit-body">
<h1>画像の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for @picture, url: pictures_path, html: { multipart: true } do |form| %>
       
       <%= form.label 'タイトル' %>
       <%= form.text_field :title %>
       
       <%= form.label '画像の設定' %>
       <%= form.file_field :avatar %>
       
       <%= form.label '画像の説明' %>
       <%= form.text_field :body %><br>
       
       <%= form.submit "画像を作成", class: "btn btn-primary"  %>
     <% end %>
     
     <%= link_to 'Show', @picture %> 
<%= link_to 'Back', pictures_path %>
  </div>
</div>

</div>

app/views/pictures/index.html.erb
<% provide(:title, "index") %>

<div class="container picture-body">
  
<div class="row">
  
  
    <% @pictures.each do |picture| %>

  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
  
  
  
    <h2><%= picture.title %></h2>
    <%= image_tag picture.avatar.url(:medium) %><br>
    <h4><span><%= picture.body %></span></h4><br>
    <button type="button" class="btn btn-info"><span><%= link_to '表示', picture_path(picture) %></button>
    <button type="button" class="btn btn-info"><span><%= link_to '編集', edit_picture_path(picture) %></span></button>
    <button type="button" class="btn btn-info"><span><%= link_to '削除', picture_path(picture),
                    method: :delete, data: { confirm: '本当に削除してよろしいですか?' } %></span></button>
  
 
 </div>
    <% end %>
    
    
</div>
 

</div>

<%= link_to '画像の新規作成', new_picture_path %>

app/views/pictures/new.html.erb
<% provide(:title, "新規作成") %>

<div class="container picture-new-body">
<h1>新規作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for @picture, url: pictures_path, html: { multipart: true } do |form| %>
       
       <%= form.label 'タイトル' %>
       <%= form.text_field :title %>
       
       <%= form.label '画像の設定' %>
       <%= form.file_field :avatar %>
       
       <%= form.label '画像の説明' %>
       <%= form.text_field :body %><br>
       
       <%= form.submit "画像を作成", class: "btn btn-primary"  %>
     <% end %>
  </div>
</div>
</div>


<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<% provide(:title, "画像の表示") %>

<div class="container pictue-show-body">
<div class="row ">
    <div class="col">
    <h2><%= @picture.title %></h2>
    <%= image_tag @picture.avatar.url(:medium) %><br>
    <%= @picture.body %>
    </div>
</div>
</div>
    
    

<%= link_to 'Back', pictures_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    
</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報の編集") %>
<h1>ユーザー情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更の確定", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>
<%= link_to 'トップページに戻る', pictures_path %>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<h1>ユーザー一覧</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, url: signup_path) do |f| %>
      
      <%= render 'shared/error_messages' %>
      
      <%= f.label '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label 'Eメール' %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label 'パスワードの確認' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>
<%= link_to 'トップページに戻る', pictures_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user%>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>

<%= link_to 'トップページに戻る', pictures_path %>